### ISSUE TITLE
Arcs vs chloropleth

### ISSUE THREAD

**Issue by nathancday** [kpivert/Carnegie-Hall-App#15]
I know we originally talked about doing both (within a tabsetPanel()), but just wanted to revisit.

Depending on the complexity involved to solve the arc-wrapping issue, chloropleths could be an easier alternative.

Since you are closer to the arc solution, it's your call. I feel like I could build a chloropleth map fairly quickly if we want to see how it would look. Holding until we chat tho.

**Comment by kpivert** [comment]
Thanks very much, Nate. I will try to fix the arcs issue. If I can't, I will add a choropleth. Will update you ASAP.

**Comment by kpivert** [comment]
@nathancday, this looks fantastic and completely works. Thanks very much. Just FYI, it threw an error when I first ran it but adding a library call to magrittr to both server and ui and a plotly call to the ui fixed the issue. Thanks again.

**Comment by kpivert** [comment]
Sorry for the extra emails. The arcs issue is exactly what I thought it was, a problem with the [dateline](https://github.com/rstudio/leaflet/issues/553). I'm examining JS options to fix this (if possible).

**Comment by nathancday** [comment]
Thanks for adding the `magtrittr` call. I can be a little sloppy with my `%<>%` usage.
