### ISSUE TITLE
Lealfet selector inspiration

### ISSUE THREAD

**Issue by nathancday** [kpivert/Carnegie-Hall-App#7]
These guys make cool Shiny apps and this one have a nice regional selector via leaflet. Migh tbe cool curb appeal.

http://outils.observatoire-des-territoires.gouv.fr/mob_resid/

**Comment by kpivert** [comment]
Holy crap. That’s really impressive. I really like how everything is integrated and there’s nothing superfluous.

**Comment by kpivert** [comment]
Nate already handled with elegant solution. See [server.R](https://github.com/kpivert/Carnegie-Hall-App/blob/master/server.R)
